### ISSUE TITLE
cannot run the sample 'drag-n-drop-charting'

### ISSUE THREAD

**Issue by archie-ex** [Esri/insights-scripting-guide#1]
Try to get the data from the pane.
But I have an error:
Error in eval(expr, envir, enclos): object 'points.salesamtho' is not found. 
(I added the sample geojson to workbook, that data set name is "points".)

**Comment by applecool** [comment]
The spatial support is currently unavailable. If you want the data to work, you should skip the geometry field and add (drag and drop) the rest of the fields from the dataset.

**Comment by archie-ex** [comment]
> 
> 
> The spatial support is currently unavailable. If you want the data to work, you should skip the geometry field and add (drag and drop) the rest of the fields from the dataset.

Once adding the AllWear.geojson at the dataset pane on Insights Home, the dataset is created as a hosted feature service.
