### ISSUE TITLE
cannot setup the gateway - error installing rpy2 with conda

### ISSUE THREAD

**Issue by segalindoa** [Esri/insights-scripting-guide#2]
This is what I get:

SpecsConfigurationConflictError: Requested specs conflict with configured specs.
  requested specs:
    - rpy2=2.8
  pinned specs:
    - python=3.7
Use 'conda config --show-sources' to look for 'pinned_specs' and 'track_features'
configuration parameters.  Pinned specs may also be defined in the file
/opt/conda/conda-meta/pinned.

**Comment by jonbodie** [comment]
The scripting guide uses python 3.6:

Step 3 under Create a gateway using Anaconda
Create an Insights Python environment using the command conda create -n my_insights_env python=3.6

Some of the packages might not be compatible with 3.7 if that is the version of Python you are using.
