### ISSUE TITLE
The ubuntu container won't handle windows authentication

### ISSUE THREAD

**Issue by simoxu001** [Esri/insights-scripting-guide#3]
My ArcGIS Enterprise is using Integrated Windows Authentication, it seems the python gateway container can't handle the windows authentication, as a result, it can't access the data sources from the ArcGIS Enterprise (Portal). 

It does sound odd to let a Linux container handle windows authentication... but I am no expert in this area.

Are there any work around for this?

**Comment by phpmaps** [comment]
@simoxu001 Thanks for your post. As we continue dev we will investigate further.  In our next beta  release coming in 3.4 the Insights web client is suppose to check which type of security configuration ArcGIS Enterprise (Portal) is using and act accordingly.  @applecool

**Comment by applecool** [comment]
Yes, this issue should be fixed in the latest release. Please feel free to re-open this issue if the issue exists in the latest software. Thanks.
