### ISSUE TITLE
Support for Plotly charts in R

### ISSUE THREAD

**Issue by tkkinlaw** [Esri/insights-scripting-guide#32]
Can support for the Plotly package for R be added? It looks like the chart_studio module is supported. Currently the R scripting environment lets you execute code to create a plotly chart, but the output is empty (and the image card).

It would be great to have the full functionality of Plotly in Insights :)

**Comment by applecool** [comment]
Thank you for the request 👍 The development work on this has been stopped. If anything changes, we will address this issue in the future. Closing this for now, thank you
