### ISSUE TITLE
Setup Scripting Environment to Connect via ArcGIS Pro Python Installation

### ISSUE THREAD

**Issue by whitacrej** [Esri/insights-scripting-guide#33]
I am running ArcGIS Insights 2022.1.x on Windows, I already have ArcGIS Pro installed, and primarily use the Python installed with ArcGIS Pro. It seems like the instructions here may require a separate Python installation to create the Jupyter Kernel Gateway even though ArcGIS Pro uses conda (not Anaconda...I know there is a difference, but I am not completely sure if that applies here). I am possibly missing something here, but is there a way to just connect ArcGIS Insights to the ArcGIS Pro Python installation? Seems like that would be the easiest implementation as I would expect most Insight users to also have ArcGIS Pro. Thanks.

**Comment by applecool** [comment]
@whitacrej Yes, you can. If you can just navigate to the ArcGIS Pro's `conda.exe` from command prompt (It should be in `C:\ProgramFiles\ArcGIS\Pro\bin\Python\Scripts`), and simply create a new environment following the rest of the steps in the instructions skipping the download and installation of anaconda. So, for creating a new environment from the yaml file, you need to put your yaml file in that Scripts folder or simply install all the packages which are in the yaml file once you activate the environment. If you have further questions, please do email me at (spamu@esri.com)
