### ISSUE TITLE
WebSocket connection failed: Error during WebSocket handshake

### ISSUE THREAD

**Issue by simoxu001** [Esri/insights-scripting-guide#4]
When use the container option, it fails to connect from Insights, while the anaconda option works.

I compared the two options, and found the cause:

The version of the jupyter gateway in anaconda is 2.1.0 , but in the pip repository, the version is 2.4.0, which will be installed when building the docker image.
So change the dockerfile to force pip to install gateway 2.1.0, it will be working.

**Comment by phpmaps** [comment]
@simoxu001 I've updated the docker file specifying the version.  Thanks for bringing this to our attention.
