### ISSUE TITLE
ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by d2rkm4n** [Esri/insights-scripting-guide#45]
Hello,

I need to use ArcGIS Insights using Python, and it has been decided to use Jupyter's Kernel Gateway via Docker.

Docker is installed and configured (a laptop using Windows 10), has been tested, and works normally. The python script selfsign.py has been created to create the scripts (by the way, I would make a change because as it is, it generates the certificate with the hostname and not the FQDN).

In the gateway folder, there is a Dockerfile, the insights-latest.yml (I assume it is not used), the README.md, the script selfsign.py, and the public key as a private key of the certificate (server.crt and server.key).

At this point, I have a doubt.
_5. Create a data folder within gateway and put your data files there._

Which files should be copied there? could you please be more explicit?
In this case, I have created the data folder and copied the same files mentioned before.

When executing it, I have errors when creating the docker image.

`docker build -t insights-gateway .`

`ERROR: failed to solve: process "/bin/bash -o pipefail -c conda install --quiet --yes     'rpy2=2.8*'     'r-base=3.4.1'     'r-irkernel=0.8*'     'r-plyr=1.8*'     'r-jsonlite=1.5*'     'r-data.table=1.11.4*'     'r-devtools=1.13*'     'r-tidyverse=1.1*'     'r-shiny=1.0*'     'r-rmarkdown=1.8*'     'r-forecast=8.2*'     'r-rsqlite=2.0*'     'r-reshape2=1.4*'     'r-nycflights13=0.2*'     'r-caret=6.0*'     'r-rcurl=1.95*'     'r-crayon=1.3*'     'r-randomforest=4.6*'     'r-htmltools=0.3*'     'r-sparklyr=0.7*'     'r-htmlwidgets=1.0*'     'r-hexbin=1.27*' &&     conda clean -tipsy &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER" did not complete successfully: exit code: 1`

At least in my case, R is not needed so I have modified the Dockerfile.

```
# Jupyter image w/ Python
FROM jupyter/scipy-notebook

LABEL maintainer="Insights"

USER root

WORKDIR /data

COPY server.crt /etc/ssl/certs/
COPY server.key /etc/ssl/certs/

# uncomment to copy data to the container
COPY /data/* /data/

USER $NB_UID

# install the kernel gateway, arcgis Python API, geopandas, msgpack, shapely, and requests
RUN pip install --quiet jupyter_kernel_gateway==2.1.0 arcgis geopandas msgpack shapely requests

# environment settings for kernel gateway
ENV KG_ALLOW_ORIGIN='*'
ENV KG_LIST_KERNELS='True'

# run kernel gateway on container start, not notebook server
EXPOSE 9999

# set tls (https) on the kernel gateway
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0", "--KernelGatewayApp.port=9999", "--KernelGatewayApp.allow_credentials='*'", "--KernelGatewayApp.allow_headers='*'", "--KernelGatewayApp.allow_methods='*'", "--KernelGatewayApp.certfile=/etc/ssl/certs/server.crt", "--KernelGatewayApp.keyfile=/etc/ssl/certs/server.key"]
```

I rebuild the Docker image, and no error messages.

`docker build -t insights-gateway .`

`[+] Building 205.5s (11/11) FINISHED docker:default => [internal] load build definition from Dockerfile 0.0s => => transferring dockerfile: 1.02kB 0.0s => [internal] load .dockerignore 0.0s => => transferring context: 2B 0.0s => [internal] load metadata for docker.io/jupyter/scipy-notebook:latest 1.0s => [1/6] FROM docker.io/jupyter/scipy-notebook@sha256:fca4bcc9cbd49d9a15e0e4df6c666adf17776c950da9fa94a4f0a045d5 0.0s => [internal] load build context 0.0s => => transferring context: 4.49MB 0.0s => CACHED [2/6] WORKDIR /data 0.0s => CACHED [3/6] COPY server.crt /etc/ssl/certs/ 0.0s => CACHED [4/6] COPY server.key /etc/ssl/certs/ 0.0s => [5/6] COPY /data/* /data/ 0.1s => [6/6] RUN pip install --quiet jupyter_kernel_gateway==2.1.0 arcgis geopandas msgpack shapely requests 202.3s => exporting to image 2.0s => => exporting layers 2.0s => => writing image sha256:e5fe6b9d09c9e3351cb86ad713959ce633ffc0714d29950f15131ad37598433e 0.0s => => naming to docker.io/library/insights-gateway 0.0s`

What's Next? View summary of image vulnerabilities and recommendations → docker scout quickview_

I start the Kernel Gateway.

`docker run -p 9999:9999 insights-gateway`

_[KernelGatewayApp] Jupyter Kernel Gateway at https://0.0.0.0:9999_

The container is created in Docker.

But when accessing.

http://localhost:9999/
https://localhost:9999/
http://server.domain.name:9999/
https://server.domain.name:9999/
http://10.1.1.2:9999/
https://10.1.1.2:9999/

I should receive a response in JSON.
{"reason": "Not Found", "message": ""}

But in this case, I have the log in Docker.

```
[KernelGatewayApp] Jupyter Kernel Gateway at https://0.0.0.0:9999
[W 240319 16:05:05 iostream:1382] SSL Error on 8 ('172.17.0.1', 49888): [SSL] internal error (_ssl.c:1006)
[W 240319 16:05:05 iostream:1382] SSL Error on 9 ('172.17.0.1', 49890): [SSL] internal error (_ssl.c:1006)
[W 240319 16:05:05 iostream:1382] SSL Error on 8 ('172.17.0.1', 49892): [SSL] internal error (_ssl.c:1006)
[W 240319 16:05:05 iostream:1382] SSL Error on 9 ('172.17.0.1', 49894): [SSL] internal error (_ssl.c:1006)
[W 240319 16:05:06 iostream:1382] SSL Error on 8 ('172.17.0.1', 49896): [SSL] internal error (_ssl.c:1006)
[W 240319 16:05:06 iostream:1382] SSL Error on 9 ('172.17.0.1', 49898): [SSL] internal error (_ssl.c:1006)
```

Any idea / recommendation to solve the issue?

Regards.

**Comment by applecool** [comment]
Hey Luis, I apologize for the late response. The docker instructions were outdated and wasn't maintained (now, removed from the repo). The recommended way of setting up the kernel is using anaconda. 
Regarding the question about data folder and the files. If let's say you have some excel or csv or any other files that you would like to access from the scripting console, you can add these files to the data folder. 
Please let me know if you have any other questions.

**Comment by d2rkm4n** [comment]
Hello @applecool 

It's a shame, I understand the possible reasons for it no longer being maintained but it is also very useful when you have an environment with Docker.

It was done with Docker for ease, but some changes had to be made.

The first thing is to create the files with the security certificate for the DNS assigned to the server. In this case the server.crt, and the server.key (can be generated using OpenSSL from a PFX file.).

Having the security certificate in the previous files, a **jupyter_kernel_gateway_config.py** file was customized to customize some details.

_c.KernelGatewayApp.allow_origin = '*'
c.KernelGatewayApp.allow_credentials = 'true'
c.KernelGatewayApp.allow_headers = 'Content-Type'
c.KernelGatewayApp.allow_methods = 'GET, POST, PUT, DELETE, OPTIONS'
c.KernelGatewayApp.certfile = '/etc/ssl/certs/server.crt'
c.KernelGatewayApp.keyfile = '/etc/ssl/private/server.key'_

With the above, have a **Dockerfile** indicating the exact versions of the libraries, the location of the certificate files and configuration aspects.

_# Using a Python base image
FROM python:3.9.14

# Install Jupyter Kernel Gateway and other dependencies
RUN pip install --quiet jupyter_kernel_gateway==2.5.1 pandas==1.5.1 shapely==1.8.5 msgpack==1.0.4 matplotlib geopandas==0.11.1 pyspark==3.3.1 arcgis requests

# Copy Jupyter Kernel Gateway configuration file
COPY jupyter_kernel_gateway_config.py /root/.jupyter/

# Copy the certificate files to the container
COPY server.crt /etc/ssl/certs/
COPY server.key /etc/ssl/private/

# Expose port 9999 for the Kernel Gateway
EXPOSE 9999

# Start Jupyter Kernel Gateway at container startup
CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0", "--KernelGatewayApp.port=9999"]_

These four files are the key.
- Dockerfile
- jupyter_kernel_gateway_config.py
- server.crt
- server.key

With that ready, the image should be created.

_$ docker build -t jupyter-kernel-gateway ._

And it starts.

_$ docker run -d -p 9999:9999 --name Jupyters_Kernel_Gateway -d jupyter-kernel-gateway_

It has been used for ArcGIS Enterprise and ArcGIS Insights, and works normally.

Regards.

**Comment by applecool** [comment]
I am glad you got it working :) I am aware of the changes that need to be made and thank you for the steps, I appreciate that.  I will add it back once I make more updates to the libraries :)
