### ISSUE TITLE
Graph labeling problems

### ISSUE THREAD

**Issue by samuello4** [Esri/insights-scripting-guide#9]
Is it possible to define a customized graph labeling that the label of a vertex is sum of the weights of incident edges and visualize the induced label by the size of the vertices? 

Moreover,  I would like to know some basics information about a graph, such as eccentricity of a vertex, edge-cut, spanning tree of a graph. 

Is there any tools/ script can solve these problems?

**Comment by applecool** [comment]
We don't offer any tools/scripts to solve the graph problems. If you would like to implement your own. You can find several online tutorials of graph algorithms on how to solve such problems.

**Comment by samuello4** [comment]
I would like to create a [Phylogeny Tree Diagram](https://urldefense.com/v3/__https:/www.gisaid.org/epiflu-applications/next-hcov-19-app/__;!!CKZwjTOV!itVqg9HL3Rru5Knjx-NAb6qXzRAqquXbHEfMGzxhhxqPOE8vUrHhndwFxX6pmQ$) in ArcGIS Insights? How can I achieve it?  
Is it possible to create non-bipartite graphs in Insights?

**Comment by applecool** [comment]
@samuello4 We currently support Link charts and Link Maps [here](https://doc.arcgis.com/en/insights/latest/create/link-chart.htm) 

Phylogeny Tree Diagrams are not a part of the current native Insights visualizations. But you can create them using any external libraries in Python using the Scripting environment. I found a few libraries like [BioPython](https://biopython.org/wiki/Phylo) , [DendroPy](https://dendropy.org/primer/index.html) . Or even better in R using [phytools](http://phytools.org/mexico2018/ex/12/Plotting-methods.html) or phylogram or ggtree

**Comment by samuello4** [comment]
Thank you so much for your kind assistance and prompt reply.
May I know whether the charts created by python/R script are interactive in insights or not?

**Comment by applecool** [comment]
Hey @samuello4 - If the chart created in the scripting environment is interactive like a plotly lib graph, then it will be interactive when you add it as a card to the Insights page. If it is a static SVG image chart like something generated from matplotlib, then it will be a static image. 

_Note: These interactive charts or graphs which you create from the Python/R libraries do not work with the native selection interactions of Insights._
